<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NORF524" failures="1" tests="2" name="Default test" time="9.381" errors="0" timestamp="2024-03-02T11:59:31 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.761"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.321">
    <failure type="java.lang.IllegalArgumentException" message="Incorrect Error Message">
      <![CDATA[java.lang.IllegalArgumentException: Incorrect Error Message
at dev.failsafe.internal.util.Assert.isTrue(Assert.java:29)
at AutomationProject.StepDefinitions.StepDefinitionImp.verify_the_errormessage(StepDefinitionImp.java:75)
at âœ½.verify the 'Sorry, this user has been locked out.'(file:///C:/Users/ADMIN/eclipse-workspace4/JavaSeleniumFramework/src/test/java/features/ErrorValidation.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
